[profile.default]
src              = 'contracts'
test             = 'test_foundry'
out              = 'artifacts_forge'
cache_path       = 'cache_forge'
libs             = ['node_modules', 'lib']
solc_version     = '0.8.26'
optimizer        = true
optimizer_runs   = 5_000
gas_reports      = ['GeniDex']

# Fuzz settings
[fuzz]
runs              = 5000
max_test_rejects  = 65536

# Invariant campaign
[invariant]
runs   = 256
depth  = 32
fail_on_revert = true
